### PR TITLE
v2 proposal

### PR DESCRIPTION
**Pull request by yanneves**
I think the suggestion to deprecate this plugin and Fathom's new integration instructions go against best practices in Gatsby.

"Plugins" may have a bad stigma attached generally (*ahem* WordPress), but they serve as a more declarative interface to customising your Gatsby instance. Since gatsby-plugin-fathom is evaluated at build-time, there's also no performance overhead. Whereas `src/html.js` is what I'd consider a 'nuclear option'. Copying a file from the build cache is a strong hint. 😄 

So I'd like to propose these changes for a version 2 of this plugin, including some breaking changes.

This proposal removes support for the v1 embed script (including support for self-hosted) to focus on only supporting the v2 embed. And since Fathom recommends using `spa="auto"` it was sensible to remove the `whitelistHostnames` option. Whitelisting use-cases should be covered by using environment variables on build-time, though.

It follows the Fathom integration to set the script tag to be loaded deferred in the head rather than post-body.

For simple use-cases setting only `siteId`, this will serve a seamless upgrade to the new v2 embed script.

Included updated README documentation and tests. Let me know what you think. ❤️

### CODE REVIEW

**Comment by yanneves** [comment]
I updated dependencies for good measure, as evidenced by the humongous `package-lock.json` diff: 😖 

image

**Comment by lgraubner** [comment]
Hi! Thanks for your PR, looking good! I'm open to keep this plugin running as far as there is demand beyond the official recommendations.

I'll look into this further and prepare a v2.

**Comment by yanneves** [comment]
hey @lgraubner, just checking whether this ticked the boxes for you, I've got a couple Gatsby projects I'm moving over to Fathom - could publish to somewhere temporary on npm like `@yanneves/gatsby-plugin-fathom` but seemed sensible to wait

**Comment by kennethormandy** [comment]
For what it’s worth, I gave this PR a try via `gatsby-plugin-fathom-v2`, and it worked great for me. I fully agree with the original comment: using a Gatsby plugin avoids a lot of potential side effects versus copying the `html.js` file.

It would be great to see this merged! Thanks for the work on this @yanneves.

**Comment by yanneves** [comment]
Thanks for the merge @lgraubner, I'll deprecate `gatsby-plugin-fathom-v2` and point it to v2 of this package 🚀

**Pull request merged**
