### PR TITLE
Fully implement the new Fathom embed code

### PR DESCRIPTION
**Pull request by meuxx**
This PR removes the old embed code implementation and updates the plugin options to match with the new fathom embed code. This is a breaking change.

Other changes:
* Add advanced options (see https://usefathom.com/support/tracking-advanced)
* Whitelist is now managed by the plugin
* The plugin now runs on development unless `disableOnDev` is set to `true`
* Expose trackPageview/blockTracking/enableTracking functions
* Add missing optional parameter `cents` to `useGoal()` hook
* Add typescript types
* Upgraded some dependencies, moved `@babel/runtime` to devDependencies

### CODE REVIEW

**Comment by meuxx** [comment]
It seems one of the Fathom employees open this PR https://github.com/lgraubner/gatsby-plugin-fathom/pull/21 saying that the project is outdated with no explanations or comments.
If this is true or not, I don't mind if this PR gets closed.

**Comment by lgraubner** [comment]
Thanks for your massive PR. Actually I currently don't have a project runnning Fathom. There is an official page which states this is not needed anymore. (https://usefathom.com/integrations/gatsbyjs)

It would be awesome, if you could test without the plugin to make sure this plugin is indeed not needed anymore.

**Comment by meuxx** [comment]
Hey sorry for my late reply.
Indeed, the new version of the official plugin works perfectly fine out of the box. It detects the route updates without any further change in Gatsby. In fact this PR removes the `onRouteUpdate()` part to let the plugin manage it.

Honestly I still think this project brings some value as it exposes some of the API (I'm talking about the useGoal hook) and it makes the setup easier.

The instructions in the [official page](https://usefathom.com/integrations/gatsbyjs) suggest overwriting `html.js` while this plugin uses the propper functions to inject the script.
> Customizing html.js is a workaround solution for when the use of the appropriate APIs is not available in gatsby-ssr.js. Consider using onRenderBody or onPreRenderHTML instead of the method above.
> https://www.gatsbyjs.org/docs/custom-html/

If you don't have any project using Fathom I would say it's better to close this PR and merge #21. I don't currently have enough time to maintain any project, sadly. Apart from that it seems they are working in [something big](https://twitter.com/usefathom/status/1272758035450957825).

**Comment by JackEllis** [comment]
@lgraubner What do you think? Or can you accept my other PR?

**Comment by lgraubner** [comment]
I will close this PR and accept your other PR. I don't have enough time right now and as long no one else needs/can maintain this I'm going to deprecate this.

**Comment by JackEllis** [comment]
@lgraubner Legend, thanks mate :)

**Pull request closed without merging**
